version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  # Redis Service
  redis:
    image: redis
    ports:
      - '6379:6379'

  # MinIO Service
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'  # S3-compatible API
      - '9001:9001'  # MinIO Console (Web UI)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data  # Persistent data storage for MinIO

  # NestJS Application Service
  app:
    build: . # Ensure you have a Dockerfile in the root
    environment:
      - MONGODB_URI=mongodb://mongo:27017/monolith-app
      - REDIS_URI=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_TOKEN_SECRET=access$
      - JWT_REFRESH_TOKEN_SECRET=refresh$
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=30
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=uploads
    depends_on:
      - mongo
      - redis
      - minio
    ports:
      - '4000:4000'

  # Prometheus Service
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - app

  # Grafana Service
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '5000:3000' # Map localhost:5000 to Grafana's internal port 3000
    depends_on:
      - prometheus

volumes:
  minio-data:
