services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'

  app: # Your NestJS application
    build: . # Ensure you have a Dockerfile in the root
    environment:
      - MONGODB_URI=mongodb://mongo:27017/monolith-app
      - REDIS_URI=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_TOKEN_SECRET=access$
      - JWT_REFRESH_TOKEN_SECRET=refresh$
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=30
    depends_on:
      - mongo
      - redis
    ports:
      - '4000:4000'
