version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  redis:
    image: redis
    ports:
      - '6379:6379'

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'  
      - '9001:9001'  
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server --console-address ":9001" /data
    volumes:
      - minio-data:/data  

  app:
    build:
      context: ./app  
      target: development  
    environment:
      - MONGODB_URI=mongodb://mongo:27017/monolith-app
      - REDIS_URI=redis
      - REDIS_PORT=6379
      - JWT_ACCESS_TOKEN_SECRET=accesssecret
      - JWT_REFRESH_TOKEN_SECRET=refreshsecret
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=30
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password123
      - MINIO_BUCKET=uploads
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=muY22hRSWxG1MbDlptrj
    depends_on:
      - mongo
      - redis
      - minio
      - elasticsearch  
    volumes:
      - ./app:/app  
      - /app/node_modules  
    command: npm run start:dev 
    ports:
      - '3000:3000' 

  prometheus:
    image: prom/prometheus
    volumes:
      - ./app/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '5000:3000' 
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0  
    environment:
      - discovery.type=single-node  
      - ELASTICSEARCH_USERNAME=admin  
      - ELASTICSEARCH_PASSWORD=123456  
    ports:
      - '9200:9200' 
    volumes:
      - esdata:/usr/share/elasticsearch/data  

volumes:
  minio-data:
  esdata:  
