apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.app.service.port }}"
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
              memory: {{ .Values.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
              memory: {{ .Values.app.resources.limits.memory }}
          env:
            {{- range .Values.app.environment }}
            {{- if .value }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- else if .valueFrom }}
            - name: {{ .name }}
              valueFrom:
{{ toYaml .valueFrom | indent 12 }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
