apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        env:
        {{- range .Values.app.environment }}
        {{- if .value }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- else if .valueFrom }}
        - name: {{ .name }}
          valueFrom:
{{ toYaml .valueFrom | indent 12 }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.app.service.port }}
