apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app
  labels:
    app: app
spec:
  maxReplicaCount: 5
  minReplicaCount: 1
  pollingInterval: 15
  scaleTargetRef:
    name: app
    kind: Deployment
    apiVersion: apps/v1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus:9090
        metricName: cpu_usage
        query: irate(process_cpu_system_seconds_total{instance=~"app:3000"}[2m]) * 100
        threshold: '40'
