apiVersion: v2
name: monolith-app
version: 1.0.0
description: Helm chart for the monolith application

sources:
  - https://github.com/MisyuraIlya/monolith_app.git

dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.21
    alias: mongo
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.12
