apiVersion: v2
name: monolith-app
version: 1.0.0
description: Helm chart for the monolith application

sources:
  - https://github.com/MisyuraIlya/monolith_app.git

dependencies:
  - name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.21
    alias: mongo
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.3.12

mongo:
  auth:
    enabled: false
  architecture: standalone
  service:
    port: 27017

redis:
  architecture: standalone
  service:
    port: 6379

minio:
  image:
    repository: minio/minio
    tag: latest
  service:
    ports:
      - 9000
      - 9001
  secret:
    name: minio-secret               
    accessKey: MINIO_ACCESS_KEY      
    secretKey: MINIO_SECRET_KEY      
  buckets:
    - name: uploads
      policy: none
      purge: false
  resources: {}

grafana:
  image:
    repository: grafana/grafana
    tag: latest
  admin:
    user: admin
    password: admin
  service:
    port: 3000

prometheus:
  image:
    repository: prom/prometheus
    tag: latest
  service:
    port: 9090
  config:
    scrape_configs:
      - job_name: 'app'
        static_configs:
          - targets: ['app:3000']

app:
  image:
    repository: spetsar/monolith-app
    tag: latest
  replicaCount: 1
  service:
    port: 3000
  environment:
    - name: MONGODB_URI
      value: "mongodb://mongo:27017/monolith-app"
    - name: REDIS_URI
      value: "redis"
    - name: REDIS_PORT
      value: "6379"
    - name: JWT_ACCESS_TOKEN_SECRET
      value: "access$"
    - name: JWT_REFRESH_TOKEN_SECRET
      value: "refresh$"
    - name: THROTTLE_TTL
      value: "60"
    - name: THROTTLE_LIMIT
      value: "30"
    - name: MINIO_ENDPOINT
      value: "http://minio:9000"
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secret
          key: MINIO_SECRET_KEY
    - name: MINIO_BUCKET
      value: "uploads"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: grafana.app.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana
              port:
                number: 3000
    - host: minio.app.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: minio
              port:
                number: 9001
    - host: app.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app
              port:
                number: 3000
